### ISSUE TITLE
Salmonella on Windows: Command "C:\Program" could not be found

### ISSUE THREAD

**Issue by zilti** [mario-goulart/salmonella#1]
On Windows the path to Salmonella has spaces in it, and that breaks Salmonella.
It assumes some C:\Program Files\Chicken Scheme\whatever path to a binary is just C:\Program.

```
Error: (string->number) bad argument type: #!eof

        Call history:

        ./setup-api.scm:462: make-parameter
        ./setup-api.scm:465: get-environment-variable
        ./setup-api.scm:782: make-parameter
        ./setup-api.scm:790: ensure-string
        ./setup-api.scm:789: ->string
        ./setup-api.scm:790: ensure-string
        ./setup-api.scm:789: ->string
        ./setup-api.scm:852: user-install-setup
        ./setup-download.scm:49: tcp-connect-timeout
        ./setup-download.scm:50: tcp-read-timeout
        ./setup-download.scm:51: tcp-write-timeout
        ./setup-download.scm:54: chicken-version
        ./setup-download.scm:54: conc
        ./setup-download.scm:64: make-parameter
        ./setup-download.scm:421: char-set
        ./setup-api.scm:467: destination-prefix         <--
```

**Comment by mario-goulart** [comment]
Hi Daniel,

Thanks for reporting that issue.  I currently don't have a Windows box at hand.  As soon as I get one I'll investigate that issue.

Can you provide the answers for the questions below?

What did you run to get that error?

How did you invoke make to build CHICKEN?

**Comment by zilti** [comment]
I just ran "salmonella" inside my project directory. I installed Chicken using https://bitbucket.org/roti/chicken-installer/downloads .

**Comment by mario-goulart** [comment]
Hi,

Sorry for the ridiculously long time to get back to you.  I've just pushed some commits that may improve the salmonella situation on Windows.

In case you are still interested, please give it a try (they are on the master branch).

Thanks for your patience.

**Comment by mario-goulart** [comment]
Forgot to mention you'll need CHICKEN 4.9.0 or newer, since older versions have a bug that affects unsetenv on Windows.
